### ISSUE TITLE
LabVIEW Version and Open to Contributions

### ISSUE THREAD

**Issue by j-medland** [RobustoSystems/ErrorManager#26]
Hi

Thanks for sharing this and your recent presentation about it at GDEV Conference Europe 2023.

Would you be able to add some info to your readme on which version of LabVIEW it is written in, if you are open to contributions and what the contribution process might be - for instance open an issue first to discuss?

Cheers

John

**Comment by RobustoSystems** [comment]
Hi John,

It was nice to meet you in person the other day. Thanks for creating this GitHub issue.

I have added the following subsections to the Readme file.
![image](https://github.com/RobustoSystems/ErrorManager/assets/34945974/ea1705c0-3ac6-4c86-b50d-f1c946e4595d)

Yes, I am open to contributions - that would be awesome. Yes, opening an issue first to discuss would be ideal. Do you have a particular feature in mind at the moment?

Thanks,
Petru

**Comment by j-medland** [comment]
That's great. Thanks

I will give it a try (once I install a newer LV version) and open an issue if I have a feature in mind.

Cheers

**Comment by RobustoSystems** [comment]
Thanks John, that sounds great.
